// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/import-xlsx/SplitPanel.tsx": () => import("../components/mockups/import-xlsx/SplitPanel.tsx"),
  "./components/mockups/import-xlsx/StepWizard.tsx": () => import("../components/mockups/import-xlsx/StepWizard.tsx")
};
